CREATE TABLE usr_group_usr (usr_id VARCHAR(50) NOT NULL, usr_group_id VARCHAR(50) NOT NULL, PRIMARY KEY (usr_id, usr_group_id))
CREATE TABLE usr_group (DESCRIPTION VARCHAR(300), usr_group_id VARCHAR(50) NOT NULL, PRIMARY KEY (usr_group_id))
CREATE TABLE USR (EMAIL VARCHAR(50) NOT NULL UNIQUE, is_enabled BOOLEAN NOT NULL, PASSWORD VARCHAR(50) NOT NULL, person_id INTEGER, usr_id VARCHAR(50) NOT NULL, PRIMARY KEY (usr_id))
CREATE TABLE room_attribute_type (DESCRIPTION VARCHAR(300), room_attribute_type_id VARCHAR(50) NOT NULL, PRIMARY KEY (room_attribute_type_id))
CREATE TABLE room_attribute (VALUE VARCHAR(50) NOT NULL, room_id VARCHAR(10) NOT NULL, room_attribute_type_id VARCHAR(50) NOT NULL, campus_id VARCHAR(255) NOT NULL, building_id VARCHAR(10) NOT NULL, PRIMARY KEY (room_id, room_attribute_type_id, campus_id, building_id))
CREATE TABLE ROOM (DESCRIPTION VARCHAR(300), room_id VARCHAR(10) NOT NULL, campus_id VARCHAR(10) NOT NULL, building_id VARCHAR(10) NOT NULL, PRIMARY KEY (room_id, campus_id, building_id))
CREATE TABLE RESERVATION (reservation_id INTEGER NOT NULL, building_id VARCHAR(10), campus_id VARCHAR(10), CREATED TIMESTAMP NOT NULL, db_status_id VARCHAR(1), MODIFIED TIMESTAMP NOT NULL, person_group_id VARCHAR(50), PURPOSE VARCHAR(300), reservation_date TIMESTAMP NOT NULL, reservation_parent_id INTEGER, room_id VARCHAR(10), time_from TIMESTAMP NOT NULL, time_to TIMESTAMP NOT NULL, usr_id VARCHAR(50), PRIMARY KEY (reservation_id))
CREATE TABLE person_group_person (person_group_id VARCHAR(50) NOT NULL, person_id INTEGER NOT NULL, PRIMARY KEY (person_group_id, person_id))
CREATE TABLE person_group (DESCRIPTION VARCHAR(300), person_group_id VARCHAR(50) NOT NULL, PRIMARY KEY (person_group_id))
CREATE TABLE PERSON (person_id INTEGER NOT NULL, family_name VARCHAR(50) NOT NULL, given_name VARCHAR(50) NOT NULL, PRIMARY KEY (person_id))
CREATE TABLE db_status (db_status_id VARCHAR(1) NOT NULL, PRIMARY KEY (db_status_id))
CREATE TABLE room_manager (room_id VARCHAR(10) NOT NULL, usr_group_id VARCHAR(50) NOT NULL, campus_id VARCHAR(10) NOT NULL, building_id VARCHAR(10) NOT NULL, PRIMARY KEY (room_id, usr_group_id, campus_id, building_id))
CREATE TABLE CAMPUS (DESCRIPTION VARCHAR(300), NAME VARCHAR(50) NOT NULL, campus_id VARCHAR(10) NOT NULL, PRIMARY KEY (campus_id))
CREATE TABLE BUILDING (DESCRIPTION VARCHAR(300), NAME VARCHAR(50) NOT NULL, campus_id VARCHAR(10) NOT NULL, building_id VARCHAR(10) NOT NULL, PRIMARY KEY (campus_id, building_id))
CREATE TABLE bookable_room (is_robot BOOLEAN NOT NULL, room_id VARCHAR(10) NOT NULL, campus_id VARCHAR(10) NOT NULL, building_id VARCHAR(10) NOT NULL, PRIMARY KEY (room_id, campus_id, building_id))
CREATE TABLE usr_group_auth (authority_id VARCHAR(20) NOT NULL, usr_group_id VARCHAR(50) NOT NULL, PRIMARY KEY (authority_id, usr_group_id))
CREATE TABLE authority (authority_id VARCHAR(20) NOT NULL, PRIMARY KEY (authority_id))
ALTER TABLE usr_group_usr ADD CONSTRAINT FK_usr_group_usr_usr_id FOREIGN KEY (usr_id) REFERENCES USR (usr_id)
ALTER TABLE usr_group_usr ADD CONSTRAINT FK_usr_group_usr_usr_group_id FOREIGN KEY (usr_group_id) REFERENCES usr_group (usr_group_id)
ALTER TABLE USR ADD CONSTRAINT FK_USR_person_id FOREIGN KEY (person_id) REFERENCES PERSON (person_id)
ALTER TABLE room_attribute ADD CONSTRAINT FK_room_attribute_room_attribute_type_id FOREIGN KEY (room_attribute_type_id) REFERENCES room_attribute_type (room_attribute_type_id)
ALTER TABLE room_attribute ADD CONSTRAINT FK_room_attribute_room_id FOREIGN KEY (room_id, campus_id, building_id) REFERENCES ROOM (room_id, campus_id, building_id)
ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_campus_id FOREIGN KEY (campus_id, building_id) REFERENCES BUILDING (campus_id, building_id)
ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_person_group_id FOREIGN KEY (person_group_id) REFERENCES person_group (person_group_id)
ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_reservation_parent_id FOREIGN KEY (reservation_parent_id) REFERENCES RESERVATION (reservation_id)
ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_usr_id FOREIGN KEY (usr_id) REFERENCES USR (usr_id)
ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_db_status_id FOREIGN KEY (db_status_id) REFERENCES db_status (db_status_id)
ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_room_id FOREIGN KEY (room_id, campus_id, building_id) REFERENCES bookable_room (room_id, campus_id, building_id)
ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_reservation_id FOREIGN KEY (reservation_id) REFERENCES RESERVATION (reservation_parent_id)
ALTER TABLE person_group_person ADD CONSTRAINT FK_person_group_person_person_group_id FOREIGN KEY (person_group_id) REFERENCES person_group (person_group_id)
ALTER TABLE person_group_person ADD CONSTRAINT FK_person_group_person_person_id FOREIGN KEY (person_id) REFERENCES PERSON (person_id)
ALTER TABLE room_manager ADD CONSTRAINT FK_room_manager_usr_group_id FOREIGN KEY (usr_group_id) REFERENCES usr_group (usr_group_id)
ALTER TABLE room_manager ADD CONSTRAINT FK_room_manager_room_id FOREIGN KEY (room_id, campus_id, building_id) REFERENCES bookable_room (room_id, campus_id, building_id)
ALTER TABLE BUILDING ADD CONSTRAINT FK_BUILDING_campus_id FOREIGN KEY (campus_id) REFERENCES CAMPUS (campus_id)
ALTER TABLE bookable_room ADD CONSTRAINT FK_bookable_room_room_id FOREIGN KEY (room_id, campus_id, building_id) REFERENCES ROOM (room_id, campus_id, building_id)
ALTER TABLE usr_group_auth ADD CONSTRAINT FK_usr_group_auth_authority_id FOREIGN KEY (authority_id) REFERENCES authority (authority_id)
ALTER TABLE usr_group_auth ADD CONSTRAINT FK_usr_group_auth_usr_group_id FOREIGN KEY (usr_group_id) REFERENCES usr_group (usr_group_id)
CREATE SEQUENCE reservation_seq START WITH 10000
CREATE SEQUENCE person_seq START WITH 10000
CREATE SEQUENCE person_seq START WITH 10000
CREATE SEQUENCE reservation_seq START WITH 10000
